import subprocess
import sys


print("=== PAPER MODE REGRESSION SUITE ===", flush=True)

test_files = [
    "tests/test_account_equity.py",
    "tests/test_paper_sim_runner_basic.py",
    "tests/test_paper_sim_runner_risk_gaps.py",
    "tests/test_paper_sim_runner_summary_serializer.py",
    "tests/test_paper_sim_runner_summary_json_serializer.py",
    "tests/test_paper_sim_runner_usd_size.py",
    "tests/test_paper_sim_runner_exit_params.py",
    "tests/test_paper_sim_runner_branch_probabilities.py",
    "tests/test_paper_sim_runner_summary_csv_serializer.py",
    "tests/test_paper_sim_runner_csv_export_path_builder.py",
    "tests/test_paper_sim_runner_summary_csv_file_export.py",
    "tests/test_closed_trades_export_rows.py",
    "tests/test_paper_sim_runner_closed_trades_csv_export.py",
    "tests/test_paper_sim_runner_export_path_builder.py",
    "tests/test_paper_sim_runner_summary_file_export.py",
    "tests/test_paper_sim_runner_export_workflow.py",
    "tests/test_paper_sim_runner_cli_export_smoke.py",
    "tests/test_paper_sim_candidate_runner.py",
    "tests/test_paper_sim_experiments.py",
    "tests/test_paper_sim_experiment_preset_batch.py",
    "tests/test_paper_sim_preset_batch_runner.py",
    "tests/test_paper_execution_adapter.py",
    "tests/test_dry_run_execution_adapter.py",
    "tests/test_live_execution_adapter.py",
    "tests/test_live_execution_workflow.py",
    "tests/test_live_safety_gate.py",
    "tests/test_live_pilot_safety.py",
    "tests/test_live_client_config.py",
    "tests/test_live_rpc_client.py",
    "tests/test_live_dex_quote_executor.py",
    "tests/test_live_cost_model.py",
    "tests/test_mechanical_safety_filter.py",
    "tests/test_mechanical_safety_profiles.py",
    "tests/test_network_reliability.py",
    "tests/test_execution_realism.py",
    "tests/test_volatility_guard.py",
    "tests/test_live_quote_cost_model_integration.py",
    "tests/test_live_execution_preview_export.py",
    "tests/test_live_execution_preview_export_cli_smoke.py",
    "tests/test_live_signed_submit_stub_executor.py",
    "tests/test_solana_command_signer_template.py",
    "tests/test_live_send_pause_reset_helper.py",
    "tests/test_live_pilot_service.py",
    "tests/test_paper_sim_runner_cost_model_integration.py",
    "tests/test_live_idempotency.py",
    "tests/test_live_order_lifecycle.py",
    "tests/test_live_audit_logger.py",
    "tests/test_live_config_validation.py",
    "tests/test_live_path_security.py",
    "tests/test_live_policy_profiles.py",
    "tests/test_live_confirmation_retry_policy.py",
    "tests/test_live_confirmation_reconciliation.py",
    "tests/test_live_retry_simulator.py",
    "tests/test_prelive_orchestrator.py",
    "tests/test_dry_run_flow_demo.py",
    "tests/test_signal_provider_stub.py",
    "tests/test_signal_provider_file.py",
    "tests/test_signal_provider_polling.py",
    "tests/test_signal_provider_dexscreener.py",
    "tests/test_dexscreener_transport.py",
    "tests/test_token_safety_filter.py",
    "tests/test_token_safety_profiles.py",
    "tests/test_prelive_risk_engine.py",
    "tests/test_prelive_service_rollup_export.py",
    "tests/test_prelive_service.py",
    "tests/test_prelive_ops.py",
    "tests/test_pilot_runbook_helper.py",
    "tests/test_paper_engine_execution.py",
    "tests/test_time_exit.py",
    "tests/test_max_daily_loss.py",
    "tests/test_max_concurrent_positions.py",
    "tests/test_weekly_summary.py",
    "tests/test_daily_summary.py",
    "tests/test_all_time_summary.py",
    "tests/test_trade_streaks.py",
    "tests/test_trade_streaks_edge_cases.py",
    "tests/test_profit_factor.py",
    "tests/test_expectancy.py",
    "tests/test_payoff_ratio.py",
    "tests/test_average_win_loss.py",
    "tests/test_gross_profit_loss.py",
    "tests/test_average_trade_pnl.py",
    "tests/test_best_worst_trade.py",
    "tests/test_median_trade_pnl.py",
    "tests/test_trade_pnl_std_dev.py",
    "tests/test_trade_pnl_variance.py",
    "tests/test_trade_pnl_coefficient_of_variation.py",
    "tests/test_downside_deviation.py",
    "tests/test_upside_deviation.py",
    "tests/test_reporting_integration_flow.py",
    "tests/test_equity_snapshot.py",
    "tests/test_settings.py",
]

result = subprocess.run(
    ["python", "-m", "pytest", "-q", *test_files]
)

print("=== REGRESSION COMPLETE ===", flush=True)
print(f"Exit Code: {result.returncode}")

sys.exit(result.returncode)
